---
- name: Keycloak installation base directroy
  debug:
    var: "keycloak_dir"

- name: Keycloak distribution url
  debug:
    var: "keycloak_dist_url"

- name: Unarchive Keycloak distribution tarball
  unarchive:
    src: "{{ keycloak_dist_url }}"
    dest: "{{ keycloak_dir }}"
    remote_src: true
    owner: "{{ keycloak_user }}"
    group: "{{ keycloak_group }}"

- name: Ensure shared directories are absent
  file:
    path: "{{ keycloak_install_dir }}/{{ item }}"
    state: absent
  with_items:
    - "standalone/data"
    - "standalone/log"

- name: Symlink shared directories
  file:
    src: "{{ keycloak_shared_dir }}/{{ item }}"
    dest: "{{ keycloak_install_dir }}/{{ item }}"
    owner: "{{ keycloak_user }}"
    group: "{{ keycloak_group }}"
    state: link
  with_items:
    - "standalone/data"
    - "standalone/log"

- name: Symlink Keycloak distribution to current link
  file:
    src: "{{ keycloak_install_dir }}"
    dest: "{{ keycloak_current_link }}"
    owner: "{{ keycloak_user }}"
    group: "{{ keycloak_group }}"
    state: link
