---
- import_tasks: prepare.yml

- name: Check if Keycloak directory already exists
  stat:
    path: "{{ keycloak_install_dir }}"
  register: keycloak_dir_stat

- import_tasks: install.yml
  when: keycloak_dir_stat.stat.exists == false

- import_tasks: service.yml
  when: keycloak_create_service == true
