---
- name: Ensure pid file directory exists
  file:
    path: /var/run/keycloak/
    state: directory

- name: Copy systemd file in place
  template:
    src: systemd/keycloak.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"
  notify: restart keycloak
